### ISSUE TITLE
Error when running 'npm run dev'

### ISSUE THREAD

**Issue by el-guero-mero** [jamesjkim88/URL-Shortener#1]
Hello James!

I tried running the app using 'npm run dev' after installing all of the dependencies using 'npm i' on the source directory, but get the following error when running the app:

****** BEGIN OUTPUT ******
|  ❭ npm run dev

> traction-assessment@1.0.0 dev /Users/mnares/WebstormProjects/URL-Shortener
> nodemon index

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index index.js`
module.js:540
    throw err;
    ^

Error: Cannot find module './config/db'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/mnares/WebstormProjects/URL-Shortener/index.js:2:19)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
[nodemon] app crashed - waiting for file changes before starting...
****** END OUTPUT ******

Is there something else I need to do or have forgotten to get this to run smoothly? My initial thought is that may need to be a /config/db file in there, as referenced in line 2 in /index.js.

Thank you,

Mateo

**Comment by el-guero-mero** [comment]
For example, should I be running mongodb already before starting this app up?

**Comment by jamesjkim88** [comment]
Hi Mateo,

Thank you for pointing that out. I added config folder into .gitignore because it shows the username and password for mongodb atlas cluster I created for the coding assessment. If you replace <username> with "test" and <password> with "test123" on config/db on the mongoURI property it should be able to work from there or you can add your own if you have your own mongodb atlas cluster. You should be able to run 'npm run dev' after on the parent directory. Please let me know if there's anything else.

Thank you!

  - James

**Comment by el-guero-mero** [comment]
Almost there, now I get a 401 Unauthorized error when trying to access the cluster ;)

**Comment by el-guero-mero** [comment]
Got it all to work, thank you!
